config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callback, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :users do
    delete 'users/sign-out', to: 'devise/sessions#destroy', as: :destroy_ruby_session
  end
  authenticate :user, lambda {|u| u.legal?} do
    root to: 'targets#index'
    namespace :admin do
      resources :targets, only: [:index, :show, :edit, :update]
    end
    resources :users
    resources :targets do
      member do
        post :force_deliver
      end
    end
    resources :delivery_schedules, only: [:index, :update]
    resources :themes
    resources :smtp_settings, only: [:edit, :update]
    resources :delivery_logs, only: [:index]
    resources :password_lists, only: [:index]
    resources :broadcasts, only: [:index, :create]
    get '/custom_chart' => 'dashboard#custom_chart'
  end
  require 'sidekiq/web'
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope(path: '/api/v1/', module: 'api_v1', as: 'v1', defaults: { format: :json }) do
    resources :records, only: :create
    resources :send_themes, only: :create
    resources :details, only: :create
  end
end

app/models/smtp_setting.rb
class SmtpSetting < ApplicationRecord
  belongs_to :theme
  has_many :accounts , dependent: :destroy

  validates_presence_of :address, :port, :domain, :user_name, :password, :authentication, :tls
  validates_numericality_of :port
  validates_inclusion_of :port, in: (0..65535).to_a
  validates_inclusion_of :tls, in: [true, false]

  accepts_nested_attributes_for :accounts, reject_if: :all_blank, allow_destroy: true
end

app/controllers/smtp_settings_controller.rb
class SmtpSettingsController < ApplicationController
  before_action :authorize_admin
  after_action :verify_authorized
  before_action :set_smtp_setting

  def edit

  end

  def update
    if @smtp_setting.update(smtp_params)
      flash[:alert] = 'success'
      redirect_to theme_path(@smtp_setting.theme)
    else
      render :edit
    end
  end

  private

  def set_smtp_setting
    @smtp_setting = SmtpSetting.includes(:accounts).find(params[:id])
  end

  def smtp_params
    params.require(:smtp_setting).permit(:address,
                                        :port,
                                        :domain,
                                        :user_name,
                                        :password,
                                        :authentication,
                                        :tls,
                                        :accounts_attributes => [:name, :id, :_destroy])
  end
end

app/helpers/smtp_settings_helper.rb
module SmtpSettingsHelper
  def set_smtp_setting(smtp_setting)
    smtp_setting.accounts.new if smtp_setting.accounts.size == 0
    smtp_setting
  end
end

app/views/smtp_settings/_smtp_setting_form.html.erb
<div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :port %>
  <%= f.number_field :port, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :domain %>
  <%= f.text_field :domain, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :user_name %>
  <%= f.text_field :user_name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.text_field :password, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :authentication %>
  <%= f.text_field :authentication, class: 'form-control' %>
</div>
<div class="form-group">
  <div class="input-field">
    <%= f.radio_button :tls, true %>
    <%= f.label :tls, 'true' %>
  </div>
  <div class="input-field">
    <%= f.radio_button :tls, false %>
    <%= f.label :tls, 'false' %>
  </div>
</div>

app/views/smtp_settings/edit.html.erb
<%= form_for set_smtp_setting(@smtp_setting), url: smtp_setting_path(@smtp_setting), method: :patch do |f| %>
    <% if @smtp_setting.errors.any? %>
        <ul>
          <% @smtp_setting.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <%= render partial: 'smtp_setting_form', :locals => { :f => f } %>
    <div class="highlight">
      <h3>accounts</h3>
      <%= f.nested_fields_for :accounts do |ff| %>
          <div class="form-group">
            <%= ff.label :name %>
            <%= ff.remove_nested_fields_link 'remove' ,class: 'btn btn-danger' %>
            <%= ff.text_field :name, :required => true, class: 'form-control' %>
          </div>
          <hr>
      <% end %>
      <%= f.add_nested_fields_link :accounts, 'add more account' %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-default' %>
    </div>
<% end %>