config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callback, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :users do
    delete 'users/sign-out', to: 'devise/sessions#destroy', as: :destroy_ruby_session
  end
  authenticate :user, lambda {|u| u.legal?} do
    root to: 'targets#index'
    namespace :admin do
      resources :targets, only: [:index, :show, :edit, :update]
    end
    resources :users
    resources :targets do
      member do
        post :force_deliver
      end
    end
    resources :delivery_schedules, only: [:index, :update]
    resources :themes
    resources :smtp_settings, only: [:edit, :update]
    resources :delivery_logs, only: [:index]
    resources :password_lists, only: [:index]
    resources :broadcasts, only: [:index, :create]
    get '/custom_chart' => 'dashboard#custom_chart'
  end
  require 'sidekiq/web'
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope(path: '/api/v1/', module: 'api_v1', as: 'v1', defaults: { format: :json }) do
    resources :records, only: :create
    resources :send_themes, only: :create
    resources :details, only: :create
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :target_themeships, dependent: :nullify
  has_many :targets, through: :target_themeships
  has_one :smtp_setting, dependent: :destroy

  accepts_nested_attributes_for :smtp_setting, reject_if: :all_blank, allow_destroy: true

  # validation
  validates_presence_of :name, :subject, :template, :website
  validates_format_of :website, with: URI::regexp(%w(http https))

  scope :for_all, -> { where(is_public: true) }
  scope :for_me, -> { where(is_public: false) }
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user!, :authorize_admin
  after_action :verify_authorized
  before_action :set_theme, only: [:show, :edit, :update]

  def index
    @themes = Theme.includes(:smtp_setting => [:accounts]).all
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(params_theme)
    if @theme.save
      flash[:alert] = 'success'
      redirect_to themes_path
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @theme.update(params_theme)
      flash[:alert] = 'success'
      redirect_to themes_path
    else
      render :new
    end
  end

  private

  def set_theme
    @theme = Theme.includes(:smtp_setting => [:accounts]).find(params[:id])
  end

  def params_theme
    params.require(:theme).permit(:name,
                                  :subject,
                                  :content,
                                  :website,
                                  smtp_setting_attributes: [:address,
                                                            :port,
                                                            :domain,
                                                            :user_name,
                                                            :password,
                                                            :authentication,
                                                            :tls])
  end
end

app/helpers/themes_helper.rb
module ThemesHelper
  def setup_smtp_setting(theme)
    theme.build_smtp_setting unless theme.smtp_setting
    theme
  end
end

app/views/themes/_theme_form.html.erb
<%= form_for setup_smtp_setting(theme), url: url, method: method do |f| %>
    <% if theme.errors.any? %>
        <ul>
          <% theme.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :template %>
      <%= f.text_field :template, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :website %>
      <%= f.url_field :website, class: 'form-control' %>
    </div>
    <div class="highlight">
      <%= f.fields_for :smtp_setting do |ff| %>
          <%= render partial: 'smtp_settings/smtp_setting_form' , :locals => {f: ff} %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-default' %>
    </div>
<% end %>

app/views/themes/edit.html.erb
<%= render partial: 'theme_form' , locals: {url: theme_path , method: :patch , theme: @theme} %>

app/views/themes/index.html.erb
<h2>Themes</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Subject</th>
    <th>Template</th>
    <th>Website</th>
    <th>account counter</th>
    <th>edit</th>
    <th>show</th>
  </tr>
  </thead>
  <tbody>
  <% @themes.each do |t| %>
      <tr>
        <td><%= t.name %></td>
        <td><%= t.subject %></td>
        <td><%= t.template %></td>
        <td><%= t.website %></td>
        <td><%= t.smtp_setting.accounts.count %></td>
        <td><%= link_to 'show', theme_path(t) , class: 'btn btn-success' %></td>
        <td><%= link_to 'edit', edit_theme_path(t) , class: 'btn btn-danger'%></td>
        <td><%= link_to 'edit email accounts', edit_smtp_setting_path(t.smtp_setting) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/themes/new.html.erb
<%= render partial: 'theme_form' , locals: {url: themes_path , method: :post , theme: @theme} %>

app/views/themes/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">名稱</div>
  <div class="panel-body"><%= @theme.name %></div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">標題</div>
  <div class="panel-body"><%= @theme.subject %></div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">內容</div>
  <div class="panel-body"><%= @theme.content %></div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">網站</div>
  <div class="panel-body"><%= @theme.website %></div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">SMTP</div>
  <div class="panel-body">
    <ul>
      <li>Address:<%= @theme.smtp_setting.address %></li>
      <li>Port:<%= @theme.smtp_setting.port %></li>
      <li>Domain:<%= @theme.smtp_setting.domain %></li>
      <li>User Name:<%= @theme.smtp_setting.user_name %></li>
      <li>PWD:<%= @theme.smtp_setting.password %></li>
      <li>Auth:<%= @theme.smtp_setting.authentication %></li>
      <li>TLS:<%= @theme.smtp_setting.tls %></li>
      <li>
        accounts <%= link_to 'edit accounts', edit_smtp_setting_path(@theme.smtp_setting) %>
        <ul>
          <% @theme.smtp_setting.accounts.each do |a| %>
              <li><%= a.name %>@<%= @theme.smtp_setting.domain %></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</div>
<%= link_to 'list for theme', themes_path, class: 'btn' %>