config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callback, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :users do
    delete 'users/sign-out', to: 'devise/sessions#destroy', as: :destroy_ruby_session
  end
  authenticate :user, lambda {|u| u.legal?} do
    root to: 'targets#index'
    namespace :admin do
      resources :targets, only: [:index, :show, :edit, :update]
    end
    resources :users
    resources :targets do
      member do
        post :force_deliver
      end
    end
    resources :delivery_schedules, only: [:index, :update]
    resources :themes
    resources :smtp_settings, only: [:edit, :update]
    resources :delivery_logs, only: [:index]
    resources :password_lists, only: [:index]
    resources :broadcasts, only: [:index, :create]
    get '/custom_chart' => 'dashboard#custom_chart'
  end
  require 'sidekiq/web'
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope(path: '/api/v1/', module: 'api_v1', as: 'v1', defaults: { format: :json }) do
    resources :records, only: :create
    resources :send_themes, only: :create
    resources :details, only: :create
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar">1</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "#", :data => { :toggle => 'dropdown' } do %>
                功能選單 <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
              <% if current_user.manager? %>
                <li><%= link_to 'Users', users_path %></li>
                <li><%= link_to '目標清單(manager)', admin_targets_path %></li>
              <% end %>
              <li><%= link_to '目標清單', targets_path %></li>
              <li><%= link_to '密碼清單', password_lists_path %></li>
              <li><%= link_to '發送排程', delivery_schedules_path %></li>
              <li><%= link_to '寄送紀錄', delivery_logs_path %></li>
              <li><%= link_to 'Line通知', user_line_notify_omniauth_authorize_path %></li>
              <li><%= link_to '送信量統計', custom_chart_path %></li>
              <% if current_user.admin? %>
                <li><%= link_to 'Broadcasts', broadcasts_path %></li>
            <% end %>
            </ul>
          </li>
          <li>
            <%= link_to '登出', destroy_ruby_session_path, :method => :delete %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="col-md-12">
      <% if flash[:notice] %>
          <div class="alert alert-success"><%= flash[:notice] %></div>
      <% end %>

      <% if flash[:alert] %>
          <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>

      <% if flash[:warning] %>
          <div class="alert alert-danger animated shake">
            <%= flash[:warning] %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
          </div>
      <% end %>

    </div>
  </div>
  <div class="container">
    <div class="col-lg-12">
        <%= yield %>
    </div>
  </div>

  </body>
</html>